### ISSUE TITLE
Project activity

### ISSUE THREAD

**Issue by willemo** [brexis/laravel-workflow#51]
There are quite a lot of open issues and PRs and I was wondering if this project is still active. @brexis might it be a good idea to add another maintainer to this project, so more people can check issues and PRs?

I'd be willing to do this and I think there might be others that would like to contribute as well.

**Comment by zerodahero** [comment]
I split my fork off to it's own package: https://github.com/zerodahero/laravel-workflow. For my needs, it was important to have metadata and a way to track dynamical workflows, which may or may not be within the scope of this project anymore. I'd be happy to help out with this repo as well, but do plan on keeping my fork active because of my specific needs.
